# Default values for fullstack-app Helm chart.
backend:
  image: chirag117/goapp:1.0.0
  replicaCount: 1
  resources:
    requests:
      cpu: 250m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  env:
    DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
  service:
    port: 8000

frontend:
  image: chirag117/nextapp:1.0.0
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  env:
    BACKEND_URL: "http://backend:8000"
  service:
    port: 3000
    type: LoadBalancer

postgres:
  image: postgres:15-alpine
  replicaCount: 1
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  env:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: postgres
  pvc:
    storage: 1Gi
  service:
    port: 5432
